FROM mcr.microsoft.com/mssql/server:2022-latest

ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Developer

WORKDIR /usr/src/app

RUN mkdir -p /var/opt/mssql/backup

COPY WebDevStd2531/WebDevStd2531.bak /var/opt/mssql/backup/WebDevStd2531.bak

USER root
COPY docker/db-entrypoint.sh /usr/local/bin/db-entrypoint.sh

RUN chmod +x /usr/local/bin/db-entrypoint.sh

USER mssql
EXPOSE 1433

ENTRYPOINT ["/usr/local/bin/db-entrypoint.sh"]
